version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=shipping_eta_info
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./msc.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
    - "5432:5432"

  scrapy:
    build: .
    command: tail -F anything
